# Generated by Django 5.1.3 on 2024-12-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mem',
        ),
    ]
