# Generated by Django 5.1.3 on 2024-12-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mem', '0002_article_delete_mem'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to='home_images/'
            ),
        ),
    ]
