# Generated by Django 3.2.17 on 2025-02-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0005_article_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
