# Generated by Django 3.2.17 on 2025-02-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0007_auto_20250205_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='home_images/',
                verbose_name='Картинка',
            ),
        ),
    ]
